CREATE TABLE IF NOT EXISTS NOBLE_WIN(
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);

INSERT INTO NOBLE_WIN(YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY)VALUES
(1970,'PHYSICS','HANNIES ALFVEN','SWEDEN','SCIENTIST'),
(1970,'PHYSICS','NEEL','FRANCE','SCIENTIST'),
(1971,'PHYSICS','PAUL','FRANCE','SCIENTIST'),
(1971,'CHEMISTRY','HAMILTON','SWEDEN','LINGUIST'),
(1972,'LITERATURE','BERNARD','GERMANY','SCIENTIST'),
(1972,'ECONOMIS','JOSEPH','RUSSIA','ECONOMIST'),
(1973,'BIOLOGY','PHILIPS','USA','PRIME MINISTER'),
(1970,'BIOLOGY','MARTIN','USA','PRESIDENT'),
(1981,'PHYSIOLOGY','HANNAH','HUNGARY','SCIENTIST'),
(1975,'PHYSICS','PETER','CHILE','SCIENTIST');

SELECT *
FROM NOBLE_WIN
WHERE SUBJECT NOT LIKE 'P%';